on:
  push:
    branch:
      - master

name: Build 

jobs:
  build: 
    name: Build latex
    runs-on: ubuntu-latest 
    container: tianon/latex
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Execute latexmk
        run: |
          latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf
