on:
  push:
    branch:
      - master

name: Build and Release

jobs:
  build: Build latex
  runs-on: tianon/latex
  steps:
    -name: Checkout code
     uses: actions/checkout@v2
    -name: Execute latexmk
     run: |
       latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf
